# Generated by Django 5.1.2 on 2024-12-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_role_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('garson', 'garson'), ('staff', 'Staff')], max_length=100),
        ),
    ]
