# Generated by Django 5.1.2 on 2024-12-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('garson', 'garson'), ('staff', 'Staff')], max_length=100),
        ),
    ]
