# Generated by Django 5.1.2 on 2025-01-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cart_food_remove_cart_quantity_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
