# Generated by Django 5.1.2 on 2025-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_employee_salary_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='food_images/default_food.jpg', upload_to='food_images/'),
        ),
    ]
