# Generated by Django 5.1.2 on 2025-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_discount_amount_order_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='preparation_time',
            field=models.PositiveBigIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
