# Generated by Django 5.1.2 on 2025-01-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_food_preparation_time_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
